//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int O_ID { get; set; }
        public int O_UserID { get; set; }
        public decimal O_TotalAmount { get; set; }
        public string O_Status { get; set; }
    }
}
